# Generated by Django 4.2 on 2024-01-29 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GenesysAuthenticator', '0003_databasepermission_table_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='databasepermission',
            name='table_alias',
            field=models.CharField(choices=[('-------', '-------'), ('admin_al', 'admin_al'), ('road_al', 'road_al'), ('val', 'val')], max_length=255),
        ),
    ]
